require("asish.plugin_config.lsp")
require("asish.plugin_config.gruvbox")
require("asish.plugin_config.lualine")
require("asish.plugin_config.nvim-tree")
require("asish.plugin_config.telescope")
require("asish.plugin_config.treesitter")
require("asish.plugin_config.autoclose")
require("asish.plugin_config.bar")
require("asish.plugin_config.dap")
require("asish.plugin_config.dap-ui")
require("asish.plugin_config.dap-virtual-text")
require("asish.plugin_config.vgit")
require("asish.plugin_config.neoformat")
require("asish.plugin_config.git-blame")

